"""empty message

Revision ID: ad9224fe19d3
Revises: ab156a6369f0
Create Date: 2026-02-02 16:34:11.018067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9224fe19d3'
down_revision = 'ab156a6369f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=120), nullable=False))
        batch_op.drop_column('ocupation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocupation', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('occupation')

    # ### end Alembic commands ###
